apiVersion: apps/v1
kind: Deployment
metadata:
  name: pit-control
  labels:
    app.kubernetes.io/name: pit-control
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount.control }}
  selector:
    matchLabels: { app: pit-control }
  template:
    metadata:
      labels:
        app: pit-control
        {{- range $k, $v := .Values.control.podLabels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      annotations:
        {{- range $k, $v := .Values.control.podAnnotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    spec:
      containers:
        - name: control
          image: {{ .Values.image.control }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 8085 }]
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/config/application.yaml
            {{- range .Values.control.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: cfg
              mountPath: /config
          livenessProbe:
            httpGet:
              path: {{ .Values.control.livenessProbe.path }}
              port: 8085
            initialDelaySeconds: {{ .Values.control.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.control.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.control.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.control.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.control.readinessProbe.path }}
              port: 8085
            initialDelaySeconds: {{ .Values.control.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.control.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.control.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.control.readinessProbe.failureThreshold }}
          resources: {{- toYaml .Values.resources.control | nindent 12 }}
      volumes:
        - name: cfg
          configMap:
            name: pit-control-config
            items:
              - key: APPLICATION_YAML
                path: application.yaml
      nodeSelector: {{- toYaml .Values.control.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.control.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.control.affinity | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.control.topologySpreadConstraints | nindent 8 }}
