{{- if .Values.ingress.gateway.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pit-gateway
  annotations:
    {{- if .Values.ingress.gateway.className }}kubernetes.io/ingress.class: {{ .Values.ingress.gateway.className }}{{- end }}
    {{- range $k, $v := .Values.ingress.gateway.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.gateway.tls }}
  tls:
  {{- toYaml .Values.ingress.gateway.tls | nindent 2 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.gateway.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: pit-gateway
                port:
                  number: {{ $.Values.service.gateway.port }}
          {{- end }}
    {{- end }}
{{- end }}
