apiVersion: v1
kind: Service
metadata:
  name: pit-gateway
  annotations:
    {{- range $k, $v := .Values.service.gateway.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.gateway.type }}
  selector: { app: pit-gateway }
  ports:
    - port: {{ .Values.service.gateway.port }}
      targetPort: 8080
      name: http
