apiVersion: v1
kind: Service
metadata:
  name: pit-control
  annotations:
    {{- range $k, $v := .Values.service.control.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.control.type }}
  selector: { app: pit-control }
  ports:
    - port: {{ .Values.service.control.port }}
      targetPort: 8085
      name: http
